# Generated by Django 5.2.1 on 2025-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('availability', models.CharField(max_length=255)),
                ('partner', models.CharField(max_length=255)),
                ('max_per_week', models.IntegerField()),
                ('max_per_month', models.IntegerField()),
                ('min_per_month', models.IntegerField()),
                ('only_days_of_month', models.JSONField(default=list)),
                ('exclude', models.CharField(max_length=255)),
                ('exclude_days_of_month', models.JSONField(default=list)),
                ('min_days_together', models.JSONField(default=list)),
            ],
        ),
    ]
