# Generated by Django 5.2.1 on 2025-05-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exclude',
            field=models.JSONField(default=list),
        ),
    ]
