# Generated by Django 5.2.1 on 2025-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0003_alter_participant_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exclude',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exclude_days_of_month',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='min_days_together',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='only_days_of_month',
            field=models.JSONField(default=None, null=True),
        ),
    ]
