# Generated by Django 5.2.1 on 2025-06-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0004_alter_participant_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='days_with_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='schedule_statistics',
            field=models.JSONField(default=list),
        ),
    ]
