# Generated by Django 5.2.1 on 2025-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0005_exhibitor_days_with_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='month',
            field=models.CharField(max_length=255),
        ),
    ]
