# Generated by Django 5.2.1 on 2025-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0006_alter_exhibitor_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='month',
            field=models.IntegerField(),
        ),
    ]
