# Generated by Django 5.2.1 on 2025-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0007_alter_exhibitor_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='partner',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
