# Generated by Django 5.2.1 on 2025-10-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0008_alter_participant_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enforced_week_days',
            field=models.JSONField(default=None, null=True),
        ),
    ]
