# Generated by Django 5.2.1 on 2025-12-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0011_sessiongroup_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='session',
            name='minute',
        ),
        migrations.AddField(
            model_name='session',
            name='end_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_minute',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
