# Generated by Django 5.2.1 on 2025-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0013_participant_id_based_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='availability',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='enforced_week_days',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exclude_ids',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exclude_session_occurrences',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='min_sessions_together',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='only_session_occurrences',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
