# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0014_add_blank_to_jsonfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('positions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='exhibitors.session')),
                ('session_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='exhibitors.sessiongroup')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='participants', to='exhibitors.participanttrait'),
        ),
    ]
