# Generated by Django 6.0.1 on 2026-05-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0015_participanttrait_participant_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='session_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='exhibitors.sessiongroup'),
        ),
        migrations.AlterUniqueTogether(
            name='exhibitor',
            unique_together={('year', 'month', 'session_group')},
        ),
    ]
