# Generated by Django 6.0.1 on 2026-05-08 10:11

from django.db import migrations


def migrate_members_to_objects(apps, schema_editor):
    Exhibitor = apps.get_model("exhibitors", "Exhibitor")
    Participant = apps.get_model("exhibitors", "Participant")

    # Build name -> id lookup
    name_to_id = dict(Participant.objects.values_list("name", "id"))

    updated = 0
    for exhibitor in Exhibitor.objects.all():
        schedule_data = exhibitor.schedule_data
        if not schedule_data:
            continue

        changed = False
        for week in schedule_data:
            sessions = week.get("sessions") or week.get("days") or []
            for session in sessions:
                members = session.get("members", [])
                if not members:
                    continue

                # Already migrated (list of dicts)
                if isinstance(members[0], dict):
                    continue

                # Convert string list to object list
                session["members"] = [
                    {"name": name, "participantId": name_to_id.get(name)}
                    for name in members
                    if name  # skip empty strings
                ]
                changed = True

        if changed:
            exhibitor.save(update_fields=["schedule_data"])
            updated += 1

    print(f"\n  Migrated schedule_data for {updated} exhibitor(s)")


def reverse_migrate(apps, schema_editor):
    Exhibitor = apps.get_model("exhibitors", "Exhibitor")

    for exhibitor in Exhibitor.objects.all():
        schedule_data = exhibitor.schedule_data
        if not schedule_data:
            continue

        changed = False
        for week in schedule_data:
            sessions = week.get("sessions") or week.get("days") or []
            for session in sessions:
                members = session.get("members", [])
                if not members:
                    continue

                if isinstance(members[0], str):
                    continue

                session["members"] = [m["name"] for m in members]
                changed = True

        if changed:
            exhibitor.save(update_fields=["schedule_data"])


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0016_exhibitor_session_group_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_members_to_objects, reverse_migrate),
    ]
