# Generated by Django 6.0.1 on 2026-05-08 10:18

from django.db import migrations


def rename_days_to_sessions(apps, schema_editor):
    Exhibitor = apps.get_model("exhibitors", "Exhibitor")
    updated = 0
    for exhibitor in Exhibitor.objects.all():
        schedule_data = exhibitor.schedule_data
        if not schedule_data:
            continue
        changed = False
        for week in schedule_data:
            if "days" in week:
                week["sessions"] = week.pop("days")
                changed = True
        if changed:
            exhibitor.save(update_fields=["schedule_data"])
            updated += 1
    print(f"\n  Renamed days->sessions in {updated} exhibitor(s)")


def reverse_rename(apps, schema_editor):
    Exhibitor = apps.get_model("exhibitors", "Exhibitor")
    for exhibitor in Exhibitor.objects.all():
        schedule_data = exhibitor.schedule_data
        if not schedule_data:
            continue
        changed = False
        for week in schedule_data:
            if "sessions" in week:
                week["days"] = week.pop("sessions")
                changed = True
        if changed:
            exhibitor.save(update_fields=["schedule_data"])


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0017_migrate_schedule_members_to_objects'),
    ]

    operations = [
        migrations.RunPython(rename_days_to_sessions, reverse_rename),
    ]
