# Generated by Django 6.0.1 on 2026-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0018_rename_days_to_sessions_in_schedule_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiongroup',
            name='scheduler_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
