# Generated by Django 6.0.1 on 2026-05-12

from django.db import migrations, models
import django.db.models.deletion


def assign_existing_to_superuser(apps, schema_editor):
    SessionGroup = apps.get_model("exhibitors", "SessionGroup")
    User = apps.get_model("auth", "User")
    # Only assign if there are session groups without a user and a superuser exists
    if SessionGroup.objects.filter(user__isnull=True).exists():
        superuser = User.objects.filter(is_superuser=True).first()
        if superuser:
            SessionGroup.objects.filter(user__isnull=True).update(user_id=superuser.id)


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitors", "0019_sessiongroup_scheduler_config"),
        ("auth", "__latest__"),
    ]

    operations = [
        # Step 1: Add user field as nullable
        migrations.AddField(
            model_name="sessiongroup",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_groups",
                to="auth.user",
            ),
        ),
        # Step 2: Populate existing rows (safe for empty DB)
        migrations.RunPython(assign_existing_to_superuser, migrations.RunPython.noop),
    ]
