# Generated by Django 6.0.1 on 2026-05-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0020_sessiongroup_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_anchor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessiongroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
