# Generated by Django 6.0.1 on 2026-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitors', '0021_add_is_anchor_to_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('name', 'session_group')},
        ),
    ]
